issueテンプレートを追加(定期券オペレーション用)
ryde-inc/.github pull request #1
Opened 2024-01-30 04:59 UTC by kayo311

## ✨ 概要
定期券登録フローの改善(ヒューマンエラーの防止）
https://github.com/ryde-inc/ryde-pass/issues/1467

## 🛠 変更内容
Issueテンプレートの作成

## 👻 影響範囲
・通常定期券追加
・いすゞ定期券追加

## 👀 重点的にレビューしてほしい箇所

## 💻 画面キャプチャ
|画面A|画面B
|---|---
|（画面キャプチャ）|（画面キャプチャ）

## ✔️ 動作確認した内容

## ☕ 補足

```<ul><li>[ ] </ul>```
でテーブル内にもチェックリストが入れられた。

2024-01-31 01:42 UTC, fumiki requested changes

2024-01-31 01:42 UTC, fumiki commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +title: "神奈中いすゞ2024-X対応"
神奈中いすゞ2024-X「対応」だと意味が広いので具体的な操作の方が誰にでも瞬時にわかりやすいかと思います。
神奈中いすゞ2024-X「企業定期券付与」とか「企業定期券配布」とか

2024-01-31 01:42 UTC, fumiki commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +about: 神奈中様向けにいすゞ定期券を追加する
初見開発者だけでなく、我々も久々に見た時に、瞬時に意味を理解しにくい懸念があるので、
「神奈中様向けにいすゞの企業定期券を付与する」
とかどうでしょう？
「追加」だと券種の追加もあるので「付与」「配布」「ユーザーに付与」など一意に定まるものがよいかなと

2024-01-31 01:42 UTC, fumiki commented on .github/ISSUE_TEMPLATE/operation_simple_pass.md
> +about: 定期券を追加する
定期券の付与と区別するために、
「pass_groupやpass_typeなどユーザーが申請可能な定期券を追加する」
とか詳しく書いてもいいかも

2024-02-01 03:07 UTC, shu-illy commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +## 📅 スケージュールと期限
（細かいとこですが…）
既存のテンプレも「スケジュール」ではなく「スケージュール」なのは意図的なものなんですかね？
@unosk @fumiki

2024-02-01 03:08 UTC, unosk commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +## 📅 スケージュールと期限
ネイティブの発音だと`skédʒuːl(` で本来スケージュールが近いんですが、、
というのは嘘で、単純に間違いです

2024-02-01 03:28 UTC, unosk requested changes

2024-02-01 03:28 UTC, unosk commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +about: 神奈中様向けにいすゞ定期券を追加する
"いすゞ従業員様向けに神奈中バスの企業定期券を付与する"はどうでしょう

> 神奈中様向けにいすゞの企業定期券を
は意味がちょっと違ってくるかなと

2024-02-01 03:28 UTC, unosk commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +## 📅 スケージュールと期限
既存のほうも直したいです

2024-02-01 03:28 UTC, unosk commented on .github/ISSUE_TEMPLATE/operation_simple_pass.md
> +## 📅 スケージュールと期限
x スケージュール
o スケジュール

2024-02-01 05:19 UTC, kayo311 commented on .github/ISSUE_TEMPLATE/operation_isuzu.md
> +## 📅 スケージュールと期限
気づいてませんでした！合わせて修正します！

2024-02-01 06:17 UTC, unosk approved these changes

2024-02-01 06:21 UTC, fumiki approved these changes

2024-02-02 05:51 UTC, shu-illy approved these changes

2024-02-02 06:21 UTC, merged